version: 1
task_definition:
  task_execution_role: ecsExecutionRole
  ecs_network_mode: awsvpc
  task_size:
    mem_limit: 0.5GB
    cpu_limit: 256
run_params:
  network_configuration:
    awsvpc_configuration:
      subnets:
        - "subnet-377ad56a"
        - "subnet-f92a579d"
      security_groups:
        - "sg-7cc39f09"
      assign_public_ip: ENABLED